# Generated by Django 5.0.4 on 2024-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0002_cart_order_orderitem_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
